# Simplified Docker Compose for AlphaStrat Trading Platform
services:
  postgres:
    image: postgres:16
    container_name: alphastrat-postgres
    environment:
      POSTGRES_DB: alphastrat
      POSTGRES_USER: alphastrat
      POSTGRES_PASSWORD: alphastrat_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: alphastrat-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alphastrat-backend
    environment:
      DATABASE_URL: postgresql://alphastrat:alphastrat_dev_password@postgres:5432/alphastrat
      REDIS_URL: redis://redis:6379
      POLYGON_API_KEY: ${POLYGON_API_KEY}
      ALPACA_API_KEY: ${ALPACA_API_KEY}
      ALPACA_SECRET_KEY: ${ALPACA_SECRET_KEY}
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    container_name: alphastrat-frontend
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_WS_URL: ws://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  postgres_data: